<?php

/**
 * @file
 * Contains moby_help_with_bundle.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function moby_help_with_bundle_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the moby_help_with_bundle module.
    case 'help.page.moby_help_with_bundle':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Moby help with bundle.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function moby_help_with_bundle_theme() {
  return [
    'moby_help_with_bundle' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function moby_help_with_bundle_theme() {
  $theme = [];
  $theme['moby_help_with_bundle_entity'] = [
    'render element' => 'elements',
    'file' => 'moby_help_with_bundle_entity.page.inc',
    'template' => 'moby_help_with_bundle_entity',
  ];
  $theme['moby_help_with_bundle_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'moby_help_with_bundle_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function moby_help_with_bundle_theme_suggestions_moby_help_with_bundle_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#moby_help_with_bundle_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'moby_help_with_bundle_entity__' . $sanitized_view_mode;
  $suggestions[] = 'moby_help_with_bundle_entity__' . $entity->bundle();
  $suggestions[] = 'moby_help_with_bundle_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'moby_help_with_bundle_entity__' . $entity->id();
  $suggestions[] = 'moby_help_with_bundle_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
